#!/usr/bin/env python


import string

def passwd_gen(length, chars):
    import os
    import random

    random.seed = (os.urandom(1024))
    password = ''.join(random.choice(chars) for i in range(length))

    return password

def main():
    import argparse

    parser = argparse.ArgumentParser(description='Pseudo-random password generator')
    parser.add_argument('-A', action = 'store_const',
                        const = string.ascii_letters,
                        default = '',
                        help = 'Password will contain ascii characters (default : yes)')
    parser.add_argument('-D', action = 'store_const',
                        const = string.digits,
                        default = '',
                        help = 'Password will contain digital characters (default : yes)')
    parser.add_argument('-S', action = 'store_const',
                        const = '`^~=|_-!?/\'"()[]{}@$*\&#%+',
                        default = '',
                        help = 'Password will contain special characters (default : yes)')
    parser.add_argument('-n', action = 'store',
                        default = 8, type = int,
                        help = 'Password size (default : %(default)s)')

    args = parser.parse_args()
    args = dict(args._get_kwargs())
    chars = args['A'] + args['D'] + args['S']
    if chars == '':
        chars = string.ascii_letters + string.digits + '`^~=|_-!?/\'"()[]{}@$*\&#%+'

    password = passwd_gen(args['n'], chars)

    print password

if __name__ == "__main__":
    main()
